server:
  port: 8092

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:customerDB
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

eureka:
  client:
    service-url:
      default-zone: http://localhost:8099/eureka/