server:
  port: 8093
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:invoiceDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka/

feign:
  hystrix:
    enabled: true
  circuitbreaker:
    enabled: true
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
management:
  endpoints:
    web:
      exposure:
        include: "*"